### PR TITLE
Sensu server registry & API /info improvements

### PR DESCRIPTION
**Pull request by portertech**
## Description

Create and update a Sensu server registry. Expose Sensu server information via the Sensu API `/info` endpoint.

## Related Issue

https://github.com/sensu/sensu/issues/1027

## Motivation and Context

Exposes information that makes it easy to troubleshoot certain issues.

## How Has This Been Tested?

RSpec and manual testing.

## Screenshots:

screenshot - 17-02-21 - 08 54 57 am

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by portertech** [comment]
Need to update `/info` specs.

**Comment by agoddard** [comment]
HAWT!!!!!!!!!

**Comment by amdprophet** [comment]
👍

**Comment by aimanparvaiz** [comment]
Looking for to it 👍

**Pull request merged**
