### PR TITLE
change master election to leader election

### PR DESCRIPTION
**Pull request by portertech**
I have been meaning to do this for a while now. This small person provided the gentle reminder: https://twitter.com/mranney/status/591807926123175936 :+1:

### CODE REVIEW

**Comment by jtimberman** [comment]
Love this. :+1:

**Comment by miah** [comment]
+1

openldap went from master/slave for replication to provider/consumer.

I think for election process, `leader` is spot on.

**Comment by portertech** [comment]
@jtimberman @miah thank you for the feedback! Going to merge this, it will be in the next release \o/

**Pull request merged**
