### PR TITLE
Fixed redaction + check client token substitution regression

### PR DESCRIPTION
**Pull request by portertech**
- Fixes https://github.com/sensu/sensu/issues/1333

### CODE REVIEW

**Comment by zbintliff** [comment]
I was trying to fix this is #1335 as well. Aren't you still modifying the check object by passing it to the substitute function?

**Comment by portertech** [comment]
@zbintliff no, initial object is duplicated, via `dup()`. Test verifies this claim. 0.25.0 will be released today :+1:

**Comment by portertech** [comment]
@zbintliff I am mistaken, there is no `dup()`, but it doesn't look like we are running into a mutation issue.

**Comment by portertech** [comment]
@zbintliff I am going to quickly patch to also use a `dup()` to cover our bases. We are only concerned about maintaining the behaviour of token subs in the check command, not the other attributes.

**Comment by portertech** [comment]
https://github.com/sensu/sensu/pull/1337

**Comment by zbintliff** [comment]
Sounds good. Thanks for swift response.

**Pull request merged**
