### PR TITLE
Implement aggregate grouping

### PR DESCRIPTION
**Pull request by roobert**
My use case is that I have multiple instances of various apps deployed to a single machine and monitored by a single sensu-client.

It's not possible to have duplicate check definitions with the same name so I've include a unique identifier in each check name, e.g: `fooapp-id-check_for_process`. When I add `aggregate: true` to my metadata, this results in the checks being written to separate buckets and not being aggregated properly.

This change allows you to specify an array of virtual check names to `aggregate:` enabling you to group checks into different (and multiple) buckets.

This builds upon the current effect of the `aggregate:` parameter and won't break existing check configs.

### CODE REVIEW

**Comment by roobert** [comment]
I've changed the implementation slightly as my initial attempt didn't take into account how the request scheduler works.

If `:aggregate` is set to a `String` then the check is assumed to be part of the specified group. Checks in an aggregate group are batched together and issued with the same `:issued` timestamp. A check can only belong to one group.

Existing behaviour is unaffected.

**Comment by Seraf** [comment]
Exactly what I need. I also suggested to use subscription as tag : https://github.com/sensu/sensu/issues/766
Thanks for your work, I hope it will be merged

**Comment by roobert** [comment]
Waiting for feedback from @portertech on this :)

**Comment by portertech** [comment]
As discussed w/ @roobert, the future of the aggregate is unclear. We may need to split the functionality into two separate primitives/endpoints, to keep things well defined/clear.

**Comment by Seraf** [comment]
Hello, any news about this feature ?

**Comment by Pryz** [comment]
Any new on this ? Thanks

**Comment by RyanJarv** [comment]
Looking into how to stop notifications based on groups of several different checks. For example if ~50% of any group of checks (one group per node, one group per service, one group per rack and one per datacenter) is down no notifications would be sent for that group. Being able to easily specify multiple aggregates would make this simple to implement.

**Comment by maxlock** [comment]
Would love to have this, please!

**Comment by calebhailey** [comment]
A proposal for "aggregates 2.0" has been published as a comment on issue #1218. Barring any objections, this proposal will be implemented in Sensu 0.24 and will resolve this PR.

**Comment by portertech** [comment]
The release/0.26 branch includes "Aggregates 2.0" and supports multiple aggregates per check :+1: Thank you all for your ideas and input! Closing this pull request.

**Pull request closed without merging**
