### PR TITLE
Configurable Sensu child process limit

### PR DESCRIPTION
**Pull request by portertech**
This pull request allows users to configure how many child processes a Sensu process can create (e.g. 20 concurrent check executions).

Example:

```
{
  "sensu": {
    "spawn": {
      "limit": 20
    }
  }
}
```

ap6gmk2

### CODE REVIEW

**Comment by portertech** [comment]
Closes https://github.com/sensu/sensu/issues/1184

**Comment by calebhailey** [comment]
New config namespace! \o/

**Comment by portertech** [comment]
Closes https://github.com/sensu/sensu/issues/1002

**Comment by portertech** [comment]
Confirmed that it works as expected.

**Comment by ctheune** [comment]
woot, thanks!

**Pull request merged**
