### PR TITLE
Aggregates 2.0

### PR DESCRIPTION
**Pull request by portertech**
Implementing https://github.com/sensu/sensu/issues/1218

- `/aggregates`

```
[
  {"name": "check_http"},
  {"name": "check_web_app"},
  {"name": "elasticsearch_health"}
]
```

- `/aggregates/elasticsearch_health`

```
{
  "clients": 15,
  "checks": 2,
  "results": {
    "ok": 18,
    "warning": 0,
    "critical": 1,
    "unknown": 0,
    "total": 19,
    "stale": 0
  }
}
```
- `/aggregates/elasticsearch_health?max_age=120`

```
{
  "clients": 15,
  "checks": 1,
  "results": {
    "ok": 18,
    "warning": 0,
    "critical": 0,
    "unknown": 0,
    "total": 19,
    "stale": 1
  }
}
```

- `/aggregates/elasticsearch_health/clients`

```
[
  {"name": "1-424242", "checks": ["elasticsearch_service","elasticsearch_cluster_health"]},
  {...}
]
```

- `/aggregates/elasticsearch_health/checks`

```
[
  {"name": "elasticsearch_service", "clients": ["1-424242","i-424243", ...]},
  {"name": "elasticsearch_cluster_health", "clients": ["1-424242"]},
  {...}
]
```

- `/aggregates/elasticsearch_health/results/critical`

```
[
  {
    "check": "elasticsearch_cluster_health", 
    "summary": [
      {
        "output": "Everything is Broken", 
        "total": 1, 
        "clients": ["i-424242"]
      }
    ]
  }
]
```

- `/aggregates/elasticsearch_health/results/critical?max_age=120`

```
[]
```

### CODE REVIEW

**Comment by calebhailey** [comment]
I AM EXCITE! \o/

**Comment by sstarcher** [comment]
I'm looking forward to aggregates not being painful

**Comment by portertech** [comment]
@solarkennedy I would love to get your thoughts on this implementation today :+1:

**Comment by calebhailey** [comment]
This LGTM. Matches our spec completely, and takes the community feedback into account RE: "stale" results. Let's ship it! :shipit:

**Comment by miah** [comment]
Exciting!

**Comment by fessyfoo** [comment]
Thought this might be handy info for someone else when reading this thread.

https://github.com/sensu/sensu/blob/98f333ef306d15e308f89988d559fb6608ae711c/lib/sensu/server/process.rb#L278-L284
```
      # Add a check result to an aggregate. The aggregate name is
      # determined by the value of check `:aggregate`. If check
      # `:aggregate` is `true` (legacy), the check `:name` is used as
      # the aggregate name. If check `:aggregate` is a string, it is
      # used as the aggregate name. This method will add the client
      # name to the aggregate, all other processing (e.g. counters) is
      # done by the Sensu API on request.
````

**Pull request merged**
