### PR TITLE
Proxy check requests

### PR DESCRIPTION
**Pull request by portertech**
Publish a check request to the configured `subscribers` (e.g. `["round-robin:snmp_pollers"]`) for every Sensu client in the registry that matches the configured client attributes in `client_attributes` on the configured `interval` (e.g. `60`). Client tokens in the check definition (e.g. `"check-snmp-if.rb -h :::address::: -i eth0"`) are substituted prior to publishing the check request. The check request check `source` is set to the client `name`.

``` json
{
  "checks": {
    "foobar": {
      "command": "check-snmp-if.rb -h :::address::: -i eth0",
      "subscribers": [
        "round-robin:snmp_pollers"
      ],
      "interval": 60,
      "proxy_requests": {
        "client_attributes": {
          "keepalive": false,
          "device_type": "router",
          "device_manufacturer": "arista"
        }
      }
    }
  }
}
```

### CODE REVIEW

**Comment by cwjohnston** [comment]
@portertech will the `request_generator` support attributes other than those in `client` scope? When I compare your example with what we do in filter definitions, it seems more consistent to nest `client` under `attributes` like this:

``` json
{
  "checks": {
    "foobar": {
      ...
      "request_generator": {
        "attributes": {
          "client": {
            "keepalive": false,
            "device_type": "router",
            "device_manufacturer": "arista"
          }
        }
      }
    }
  }
}
```

**Comment by portertech** [comment]
@cwjohnston the feature is limited to the client registry and therefore only the client definition scope.

**Comment by portertech** [comment]
Now to work out naming things and configuration scope.

**Comment by cwjohnston** [comment]
Closes #1259 
Closes #1278

**Comment by exeral** [comment]
from what I undertsand,
this check config
```
      "proxy_requests": {
        "client_attributes": {
          "keepalive": false,
          "device_type": "router",
          "device_manufacturer": "arista"
        }
```
means that it matches all clients like:
```
 "client": {
    "address": "10.1.2.3",
    "name": "switch1",
    "device_type": "router",
    "device_manufacturer": "arista"
    "keepalive": {
    },
    "subscriptions": [
      "default",
      "virtual",
      "another-subscription"
    ]
  }
```
```
 "client": {
    "address": "10.1.2.4",
    "name": "switch2",
    "device_type": "router",
    "device_manufacturer": "arista"
    "keepalive": {
    },
    "subscriptions": [
      "default",
      "another-subscription"
    ]
  }
```
???

so the snmp_poller will do
`check-snmp-if.rb -h 10.1.2.3 -i eth0`
`check-snmp-if.rb -h 10.1.2.4 -i eth0`

I'm right ?

**Comment by cwjohnston** [comment]
@exeral you have the right idea 👍 

Note that the clients would also need `"keepalive": false` instead of `"keepalive": {}` in order to match.

**Comment by exeral** [comment]
great ! that's what I was looking for

**Comment by x70b1** [comment]
Very nice to see a progress on this topic.
exeral show us already an example. But does it work with subscriptions also?

Like this? I define a client and add a subscription.

```
curl -s -i -X POST -H 'Content-Type: application/json' -d '{"name": "web.server", "address": "12.23.34.45", "subscriptions":["webservers"]}' http://127.0.0.1:123/clients

```
{
  "checks": {
    "snmp": {
      "command": "check-snmp-if.rb -h :::address::: -i eth0",
      "subscribers": [
        "webserver"
      ],
      "interval": 60,
      "proxy_requests": {
        "client_attributes": {
          "keepalive": false
        }
      }
    }
  }
}
```

**Comment by Gillingham** [comment]
This would be much more useful with #1371 supported as well, having to write a bunch of API requests every time the sensu data clears out for things like static clients is a bit of a pain vs just defining them in a configuration file.

**Comment by dreamerm99** [comment]
Hi, I was wondering if there is a more detailed example on how to configure configs for external proxy client?  I see the example you had in documentation that utilizes client_attributes to filter with clients with the matched tags, and then executes the check against those client's address with the toke :::address:::.  


Where would I define configuration for external clients so the check config will be able to pull its address to perform checks?

**Comment by xblitz** [comment]
any updates on the adding of defining static clients for use with the Proxy checks requests?
Since our sensu setup is installed via chef and everything is automated, it would be great if there was a simple way of defining all of the static client without doing API Calls

**Comment by exeral** [comment]
Hi, I have the same problem. I'm wondering how to monitor dozen of snmp devices. I don't understand how/where they should be created (especially via puppet)
every doc talks about proxy client, but can I create proxy client through puppet ?

**Pull request merged**
