### PR TITLE
Pull concurrent_workers setting from client settings

### PR DESCRIPTION
**Pull request by mnguyen1289**
Allows sensu clients to set the max number of concurrent event machine workers.

Needs this pull request as well: https://github.com/sensu/sensu-spawn/pull/12

Resolves sensu/sensu#1184

### CODE REVIEW

**Comment by portertech** [comment]
@mnguyen1289 the concurrency limitation can also apply to the Sensu server (pipe handlers and mutators), perhaps it's time we added a separate definition scope for this sort of configuration? Stumped on naming.

**Comment by calebhailey** [comment]
@portertech what's wrong with a `sensu` configuration scope? As long as we are careful to only use the `sensu` configuration scope for functions that are shared across all of the Sensu processes (e.g. sensu-client, sensu-server, sensu-api, sensu-enterprise). Thoughts?

**Comment by mnguyen1289** [comment]
@portertech @calebhailey I've updated the spawn options to pull from a eventmachine json dictionary. I've also included in the server handlers/mutators to pull from there as well.

Let me know if that makes more sense than putting it from within the client settings

**Comment by portertech** [comment]
Closing this pull-request, as similar functionality was added in 0.24 https://github.com/sensu/sensu/blob/master/CHANGELOG.md#0240---2016-06-06, e.g. `{"sensu": {"spawn": {"limit": 50}}}` https://github.com/sensu/sensu/blob/master/lib/sensu/daemon.rb#L166

**Pull request closed without merging**
