### PR TITLE
Added standalone_mode, clients do not subscribe to the queue in this …

### PR DESCRIPTION
**Pull request by runningman84**
…case (important for snssqs transport)

### CODE REVIEW

**Comment by runningman84** [comment]
@portertech can you give me a hint what is failing the tests? The client, server and api works fine in my machine with this modifications?

**Comment by syepes** [comment]
@runningman84 Is adding this feature going to be compatible with https://github.com/sensu/sensu-transport/issues/36? I will be creating a pull in the following weeks

**Comment by runningman84** [comment]
@syepes I do not see a reason why this feature would not be compatible. The standalone mode just ensure that the clients itself do not receive anything from the queue. This was important for us in order to use special transports like snssqs safely.

**Comment by syepes** [comment]
@runningman84 Effectively it should still work if the client is still sending its data to the results queue.

**Comment by runningman84** [comment]
@portertech I would really appreciate an answer.

**Comment by runningman84** [comment]
@calebhailey maybe you can take a look?

**Comment by portertech** [comment]
@runningman84 why does the transport need a mode? I can see the reasoning behind disabling client subscriptions.

**Comment by portertech** [comment]
These changes would cause issues with several 0.26 features, such as https://github.com/sensu/sensu/issues/1327, which the upcoming built-in silencing feature depends on https://github.com/sensu/sensu/issues/1328

**Comment by portertech** [comment]
Why is this "important for snssqs transport"?

**Comment by runningman84** [comment]
The full explanation can be found here:
https://github.com/SimpleFinance/sensu-transport-snssqs/issues/5

A transport mode would be useful to do stuff like this
```
        case @settings[:mode]
        when 'client'
          raise("transport does not work without sns client, please specify publishing_sns_topic_arn") if @sns.nil?
        when 'server'
          raise("transport does not work without sqs client, please specify consuming_sqs_queue_url") if @sqs.nil?
        end
```

My understanding is that the upcoming changes in 0.26 would add a client:instance-id subscription to each instance. This is not a problem if the standalone mode would be included. Otherwise we would have problems because snssqs does only work if the client has empty subscriptions.

**Comment by runningman84** [comment]
This is not needed anymore if the pull request in snssqs transport gets merged.

**Pull request closed without merging**
