### PR TITLE
Allow extension handlers to have `filters`.

### PR DESCRIPTION
**Pull request by nhooey**

### CODE REVIEW

**Comment by nhooey** [comment]
#1282 depends on this change.

**Comment by nhooey** [comment]
With this change, an extension handler can defined its own instance method to return `filter` or `filters`, but this issue needs to be solved to get it from configuration: sensu/sensu-settings#30.

**Comment by portertech** [comment]
@nhooey Sensu handler extensions do support filters. Add "filter" or "filters" to `definition()`.

**Comment by nhooey** [comment]
What do you mean by `definition()`? Could you be more specific?

Is `definition()` a member function of the Extension handler class? Is `definition()` a section in a `handler` definition in the JSON configuration?

Since my handler is an extension handler, it's not defined in the configuration JSON, only mentioned in the `handlers` section of each `check`.

**Comment by nhooey** [comment]
For anyone else looking at this, it's the `definition()` member function of the extension handler where the `filters` entry is set. So my pull request isn't needed.

**Pull request closed without merging**
