### PR TITLE
updating outdated parse-cron gem

### PR DESCRIPTION
**Pull request by oscar123mendoza**
https://github.com/oscar123mendoza/parse_cron

## Description
I am updating the gem to be able to handle 5, 6, and 7 field cron jobs. 

## Motivation and Context
I use dkron as a cron job scheduler and all crons are written into 7 digit cron jobs and this would add that support for sensu.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by oscar123mendoza** [comment]
@majormoses This is from the discussion we had in the slack channel

**Comment by majormoses** [comment]
I double checked and the settings validator will not also need an update: https://github.com/sensu/sensu-settings/blob/v10.15.0/lib/sensu/settings/validators/check.rb#L48-L61

**Comment by majormoses** [comment]
@portertech @amdprophet @cwjohnston any concerns with this? I'd rather take something being maintained.

**Comment by annaplotkin** [comment]
Hi there! At this time, given that there are no known issues with the parse-cron gem and Sensu 1.x is in maintenance mode (Discourse post with details here: https://discourse.sensu.io/t/the-eol-schedule-for-sensu-core-1-x-and-sensu-enterprise-3-x/1222) we are not going to accept this PR at this time. We appreciate the effort and contribution!

**Comment by majormoses** [comment]
@annaplotkin why would we not accept this? it's not EOL until the new year (2020) and there is no details given (outlined in blog, discourse, etc) in terms of cut off for new code in terms of features, bug fixes, security, etc. If the expectation is that its not EOL until 2020 then it should be maintained as such or clearly outlined what types of changes will be accepted by what cut off.

I really don't want to have to fork and maintain sensu until December if I don't have to.

**Comment by annaplotkin** [comment]
@majormoses Thanks for reaching out and great question! Happy to help clarify. Sensu 1.x is in maintenance mode currently with EOL in December of this year (2019). Maintenance mode in this context means that only critical bug fixes and security patches are being accepted/developed at this time. In the blog post here (https://blog.sensu.io/eol-schedule-for-sensu-core-and-enterprise) in the 'Looking Back' section, Caleb provided a few details around this. Our goal is absolutely not to create confusion and definitely appreciate your feedback on how to make this more clear. We will look into updating the Discourse post and README with your suggestions on acceptance criteria for code and relevant dates 👍 Hope that helps but please feel free to reach out to me on Slack or via email if needed!

**Pull request closed without merging**
