### PR TITLE
sensu-install -c/--clean cli option to clean gems

### PR DESCRIPTION
**Pull request by portertech**
```
$ ./exe/sensu-install -h
Usage: sensu-install [options]
    -h, --help                       Display this message
    -v, --verbose                    Enable verbose logging
    -p, --plugin PLUGIN              Install a Sensu PLUGIN
    -P, --plugins PLUGIN[,PLUGIN]    PLUGIN or comma-delimited list of Sensu plugins to install
    -e, --extension EXTENSION        Install a Sensu EXTENSION
    -E, --extensions EXTENSION[,EXT] EXTENSION or comma-delimited list of Sensu extensions to install
    -s, --source SOURCE              Install Sensu plugins and extensions from a custom SOURCE
    -c, --clean                      Clean up (remove) other installed versions of the plugin(s) and/or extension(s)
```

### CODE REVIEW

**Comment by portertech** [comment]
Example usage output:

```
$ ./exe/sensu-install -e snmp-trap:0.0.4
[SENSU-INSTALL] installing Sensu extensions ...
[SENSU-INSTALL] determining if Sensu gem 'sensu-extensions-snmp-trap:0.0.4' is already installed ...
false
[SENSU-INSTALL] Sensu extension gems to be installed: ["sensu-extensions-snmp-trap:0.0.4"]
[SENSU-INSTALL] installing Sensu gem 'sensu-extensions-snmp-trap:0.0.4'
Fetching: sensu-extensions-snmp-trap-0.0.4.gem (100%)
Successfully installed sensu-extensions-snmp-trap-0.0.4
1 gem installed
[SENSU-INSTALL] successfully installed Sensu extensions: ["sensu-extensions-snmp-trap:0.0.4"]

$ ./exe/sensu-install -e snmp-trap:0.0.4 -c
[SENSU-INSTALL] installing Sensu extensions ...
[SENSU-INSTALL] determining if Sensu gem 'sensu-extensions-snmp-trap:0.0.4' is already installed ...
true
[SENSU-INSTALL] Sensu gem 'sensu-extensions-snmp-trap' has already been installed
[SENSU-INSTALL] Sensu extension gems to be installed: []
[SENSU-INSTALL] successfully installed Sensu extensions: []
[SENSU-INSTALL] cleaning Sensu gem 'sensu-extensions-snmp-trap:0.0.4'
[SENSU-INSTALL] determining installed versions of Sensu gem 'sensu-extensions-snmp-trap' ...
[SENSU-INSTALL] Sensu gem 'sensu-extensions-snmp-trap' version '0.0.4' is the only version installed
Cleaning up installed gems...
Clean Up Complete
[SENSU-INSTALL] successfully cleaned Sensu gem 'sensu-extensions-snmp-trap'

$ ./exe/sensu-install -e snmp-trap:0.0.5 -c                      
[SENSU-INSTALL] installing Sensu extensions ...
[SENSU-INSTALL] determining if Sensu gem 'sensu-extensions-snmp-trap:0.0.5' is already installed ...
false
[SENSU-INSTALL] Sensu extension gems to be installed: ["sensu-extensions-snmp-trap:0.0.5"]
[SENSU-INSTALL] installing Sensu gem 'sensu-extensions-snmp-trap:0.0.5'
Fetching: sensu-extensions-snmp-trap-0.0.5.gem (100%)
Successfully installed sensu-extensions-snmp-trap-0.0.5
1 gem installed
[SENSU-INSTALL] successfully installed Sensu extensions: ["sensu-extensions-snmp-trap:0.0.5"]
[SENSU-INSTALL] cleaning Sensu gem 'sensu-extensions-snmp-trap:0.0.5'
[SENSU-INSTALL] determining installed versions of Sensu gem 'sensu-extensions-snmp-trap' ...
Successfully uninstalled sensu-extensions-snmp-trap-0.0.4
[SENSU-INSTALL] successfully cleaned Sensu gem 'sensu-extensions-snmp-trap'

$ ./exe/sensu-install -p pagerduty
[SENSU-INSTALL] installing Sensu plugins ...
[SENSU-INSTALL] determining if Sensu gem 'sensu-plugins-pagerduty' is already installed ...
false
[SENSU-INSTALL] Sensu plugin gems to be installed: ["sensu-plugins-pagerduty"]
[SENSU-INSTALL] installing Sensu gem 'sensu-plugins-pagerduty'
Fetching: pagerduty-2.1.0.gem (100%)
If upgrading to pagerduty 2.0.0 please note the API changes:
https://github.com/envato/pagerduty#upgrading-to-version-200
Successfully installed pagerduty-2.1.0
Fetching: sensu-plugins-pagerduty-2.0.0.gem (100%)
You can use the embedded Ruby by setting EMBEDDED_RUBY=true in /etc/default/sensu
Successfully installed sensu-plugins-pagerduty-2.0.0
2 gems installed
[SENSU-INSTALL] successfully installed Sensu plugins: ["sensu-plugins-pagerduty"]

$ ./exe/sensu-install -p pagerduty -c
[SENSU-INSTALL] installing Sensu plugins ...
[SENSU-INSTALL] determining if Sensu gem 'sensu-plugins-pagerduty' is already installed ...
true
[SENSU-INSTALL] Sensu gem 'sensu-plugins-pagerduty' has already been installed
[SENSU-INSTALL] Sensu plugin gems to be installed: []
[SENSU-INSTALL] successfully installed Sensu plugins: []
[SENSU-INSTALL] cleaning Sensu gem 'sensu-plugins-pagerduty'
Cleaning up installed gems...
Clean Up Complete
[SENSU-INSTALL] successfully cleaned Sensu gem 'sensu-plugins-pagerduty'
```

**Comment by agoddard** [comment]
👍 I like it

**Comment by portertech** [comment]
Closes https://github.com/sensu/sensu/issues/1490

**Comment by amdprophet** [comment]
👍

**Comment by echavrey** [comment]
It indeed displays the message of cleaning the plugin, but actually it's not working. 
When installing, then using an only cleaning command and finally installing again, the determining if Sensu Gem is already installed returns True (which implies that the gem has never been deleted). 

Onamae wa erroru desu

**Pull request merged**
