### PR TITLE
client http_socket improvements and testing

### PR DESCRIPTION
**Pull request by portertech**
This pull request makes improvements upon the work done in https://github.com/sensu/sensu/pull/1488 and adds much needed tests.

### CODE REVIEW

**Comment by portertech** [comment]
Waiting on https://github.com/sensu/sensu-settings/pull/54

**Comment by portertech** [comment]
Going to pick this back up in the AM :+1:

**Comment by portertech** [comment]
Ready for review :+1:

**Comment by amdprophet** [comment]
giphy

**Pull request merged**
