### PR TITLE
Make event IDs persist until the event is resolved

### PR DESCRIPTION
**Pull request by portertech**
This pull request makes Sensu event IDs persist, for one or more event occurrences, until the event is resolved. This closes https://github.com/sensu/sensu/issues/1196

This makes event IDs useful, beyond just an event occurrence identifier.

### CODE REVIEW

**Comment by amdprophet** [comment]
:+1:

**Comment by portertech** [comment]
730147c4-7560-11e4-9375-fefd2f67563b

**Comment by calebhailey** [comment]
I'm excited about this change. I can't wait to see what people build with this. 

/cc @solarkennedy and @joshzitting

**Comment by mattyjones** [comment]
I need this, this is great!

**Pull request merged**
