### PR TITLE
Client socket accepts multiple checks in one request.

### PR DESCRIPTION
**Pull request by autumnw**
Make sensu client can accept multiple checks through client sockets(HTTP and TCP)

## Description

If user needs to push lots of results through client socket in one request, it will improve the client socket performance a lot. 
This patch will allow the HTTP and TCP socket receive the data as array of checks.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by portertech** [comment]
Hey @autumnw, if you could please remove your changelog addition (adding an entry is part of the release process) and add at test or two? Once this is done, we can merge.

**Comment by autumnw** [comment]
Thanks portertech ! I will get it done during this weekend.

**Comment by autumnw** [comment]
@ portertech, I removed the change in hangelog and also added 2 its. 
One quick question: When I run rspec locally for http_client tests, always got error:
Looks like fails on local @client.setup_transport.  Is there any special thing I need to setup to make it work?
[root@salt sensu]# bundle exec rspec spec/client/http_socket_spec.rb 
FF

Failures:

  1) Sensu::Client::HTTPSocket can provide basic version and transport information
     Failure/Error: async_wrapper do
     RuntimeError:
       test timed out
     # ./spec/helpers.rb:67:in `block (2 levels) in async_wrapper'
     # ./spec/helpers.rb:59:in `block in timer'
     # ./spec/helpers.rb:65:in `async_wrapper'
     # ./spec/client/http_socket_spec.rb:14:in `block (2 levels) in <top (required)>'

**Comment by portertech** [comment]
@autumnw are Redis and RabbitMQ running on your local machine? Could be that the test requires those services.

**Comment by majormoses** [comment]
@autumnw FYI we just had a discussion and are gonna standardized the changelog conventions shortly so that you will include a changelog entry under unreleased same as plugins on future PRs.

**Comment by autumnw** [comment]
Great!  Thanks @portertech

**Comment by portertech** [comment]
Going to merge this, make a minor change, and add a changelog entry 👍 

@autumnw Thank you for the PR! 🎉 

@majormoses Thank you for reviewing!

**Pull request merged**
