### PR TITLE
API created clients may be expected to produce keepalives (eventually)

### LINKED ISSUE #1203: Creating a new client through the API disables `keepalives`.
When I create a new client that doesn"t already exist in the API:
**`POST /clients`:**
```json
{
    "name": "<name>",
    "address": "<ip_address>"
}
```

I get `keepalives` disabled in the client:
**`GET /clients/<name>`:** 
```json
{
    "address": "<ip_address>",
    "keepalives": false,
    "name": "<name>",
    "subscriptions": [],
    "timestamp": 1459539874,
    "version": "0.22.1"
}
```

Why are `keepalives` set to false by default?

Even when I enabled `keepalives`, specify the `default` `handler`, and specify thresholds for `keepalive`:
**`POST /clients`:**
```json
{
    "name": "<name>",
    "address": "<ip_address>",
    "keepalives": true,
    "keepalive": {
        "handlers": ["default"],
        "thresholds": {
            "critical": 180,
            "warning": 60
        }
    }
}
```

I still get a client with `keepalives` disabled:
**`GET /clients/<name>`:**
```json
{
    "address": "<ip_address>",
    "keepalive": {
        "handlers": ["default"],
        "thresholds": {
            "critical": 180,
            "warning": 60
        }
    },
    "keepalives": false,
    "name": "<name>",
    "subscriptions": [],
    "timestamp": 1459540464,
    "version": "0.22.1"
}
```

### PR DESCRIPTION
**Pull request by portertech**
Closes #1203

### CODE REVIEW

**Comment by amdprophet** [comment]
:+1:

**Comment by calebhailey** [comment]
@portertech shouldn't the test set some keepalive thresholds and wait to see if a keepalive event is created?

**Comment by calebhailey** [comment]
Other than that, I'm pretty excited about this and I think @nhooey and many others are going to be as well. 👍

**Comment by portertech** [comment]
@calebhailey this is an api spec test, not for server keepalive monitoring, which already has tests.

**Comment by portertech** [comment]
@calebhailey these clients will get picked up with default thresholds, unless the post body also includes client keepalive configuration information, which isn't currently validated :-1:

**Comment by portertech** [comment]
Now I remember why I didn't like this :P

**Comment by portertech** [comment]
Going to be working on https://github.com/sensu/sensu/issues/1244 tomorrow. Afterwards, we can add some direct access to "validators", so we can properly validate the POST /clients body :+1:

**Comment by portertech** [comment]
Back to working on this :+1:

**Comment by portertech** [comment]
Ready for review :+1:

**Comment by portertech** [comment]
catwalk

**Comment by amdprophet** [comment]
👍

**Pull request merged**
