### PR TITLE
Official Docker image (CentOS 7 based)

### PR DESCRIPTION
**Pull request by portertech**
Inspired by @sstarcher's [Debian based Docker image](https://github.com/sstarcher/docker-sensu).

### CODE REVIEW

**Comment by cjchand** [comment]
Greatness! Would love to stop building this myself, so happy to see a CentOS container might become official :)

Any thoughts on adding a docker-compose.yml to this so we can have RMQ and Redis readily available? Makes for a really nice user experience, especially for folks new to Sensu, to simply type `docker-compose up` and have a fully-working setup.

Maybe best left outside of the core effort, but maybe something to consider: I really like the construct of having a text file (e.g.: `sensu-plugins`) that you can use to bake in any required plugins at build time, ala:
`RUN for plugin in $(cat /sensu-plugins); do sensu-install -P $plugin; done`

Shane's currently does something similar at runtime, but my preference is to bake it into the image, thus speeding recovery times if/when the container dies.

Anyway, just food for thought. LMK if you want/need input or assistance on this effort. Near and dear to my ❤️

**Comment by sstarcher** [comment]
@cjchand my supports it at runtime or preferably at build time when a user uses it as a base image.  I highly recommend against doing it at runtime for anything, but testing.

Another large difference that might make a difference for people is with no templating in the base container.

Any reason for CentOS as the base it's typically a very uncommon base image to use.

**Comment by cjchand** [comment]
@sstarcher Ah, sorry for my confusion on the build vs run time bit.

**Comment by portertech** [comment]
Merging this first pass at an official docker CentOS image. We can always create issues for desired changes and functionality.

tumblr_mvrc0evts81swhepeo1_250_zps371b1695

**Pull request merged**
